
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files (x86)/CMake/cmake-3.29.1-windows-x86_64/share/cmake-3.29/Modules/CMakeDetermineSystem.cmake:205 (message)"
      - "CMakeLists.txt:2 (project)"
    message: |
      The system is: Windows - 10.0.22631 - AMD64
...
